apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2-1
spec:
  selector:
    matchLabels:
      app: nginx-2-1
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-2-1
    spec:
      containers:
      - name: nginx-2-1
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      initContainers:
      - name: init-nginx-2-1
        image: busybox
        command: ['sh', '-c', 'until nslookup nginx-2-1-svc.netology.svc.cluster.local; do echo waiting for nginx-2-1-svc; sleep 2; done;']